import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import dynamic from 'next/dynamic';
const Footer = dynamic(() => import('./(home)/_components/Footer'), {
  ssr: false,
});
const ClientProviders = dynamic(() => import('@/providers/ClientProvider'), {
  ssr: false,
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Now Digital Easy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={inter.className}>
        <ClientProviders>
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
